# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: right_hand_group
  joint_model_group_pose: fighting_pose
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - bum_zlj
    - bum_xlj
    - bum_ylj
    - knee_left
    - ankle_lj
    - foot_lj
    - bum_zrj
    - bum_xrj
    - bum_yrj
    - knee_right
    - ankle_rj
    - foot_rj
    - shoulder_zlj
    - shoulder_xlj
    - shoulder_ylj
    - forearm_ylj
    - shoulder_zrj
    - shoulder_xrj
    - shoulder_yrj
    - forearm_yrj
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: left_leg_group_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - bum_zlj
      - bum_xlj
      - bum_ylj
      - knee_left
      - ankle_lj
      - foot_lj
  - name: right_leg_group_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - bum_zrj
      - bum_xrj
      - bum_yrj
      - knee_right
      - ankle_rj
      - foot_rj
  - name: left_hand_group_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - shoulder_zlj
      - shoulder_xlj
      - shoulder_ylj
      - forearm_ylj
  - name: right_hand_group_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - shoulder_zrj
      - shoulder_xrj
      - shoulder_yrj
      - forearm_yrj